 name: my first github action workflow

 on: [workflow_dispatch]

 jobs:
    first_jobs: #first job
       runs-on: ubuntu-latest
       steps: 
          - name: say hello world
            run: echo "Hello World"

          -  name: display user
             run: echo (whoami)
